# Configuration related to self-hosted runner.
self-hosted-runner:
  # Labels of self-hosted runner in array of strings.
  labels:
    - self-hosted
    - official-aiu-x86-64-arc-runner-set-v1
    - official-aiu-x86-64-arc-runner-set-v2
    - official-aiu-x86-64-arc-runner-set-v3
    - official-aiu-x86-64-arc-runner-set-v4
    # add separate categories
    - runner_v4
    - x86_64
    - amd64
    - spyre_card_pf
    - spyre_backend_image
