# Copyright 2025 The Torch-Spyre Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import logging

from sympy import Symbol


import torch
from .logging_utils import get_inductor_logger
from torch._inductor.ir import (
    ComputedBuffer,
    FallbackKernel,
    FixedLayout,
    InputBuffer,
    MultiOutput,
    Pointwise,
    Reduction,
    StorageBox,
    TensorBox,
)
from torch._inductor.scheduler import (
    BaseSchedulerNode,
    SchedulerNode,
    ExternKernelSchedulerNode,
    NopKernelSchedulerNode,
)
from torch._inductor.virtualized import V

from torch_spyre._C import (
    SpyreTensorLayout,
    get_device_dtype,
    get_elem_in_stick,
)
from .errors import Unsupported
from .constants import MATMUL_REDUCTION_OP, BATCH_MATMUL_OP
from .ir import FixedTiledLayout
from .pass_utils import (
    SchedNodeArg,
    get_mem_deps,
    host_coordinates,
    device_coordinates,
)

logger = get_inductor_logger("stickify")

aten = torch.ops.aten
spyreop = torch.ops.spyre


def is_sparse(stl: SpyreTensorLayout) -> bool:
    return stl.dim_map[-1] == -1


def device_layout_like(
    layout: FixedTiledLayout, dtype: torch.dtype
) -> SpyreTensorLayout:
    """
    Return a SpyreTensorLayout with the same tiling pattern as layout adjusted for the device_size of dtype.
    """
    if get_elem_in_stick(layout.dtype) == get_elem_in_stick(dtype):
        return SpyreTensorLayout(
            layout.device_layout.device_size,
            layout.device_layout.dim_map,
            get_device_dtype(dtype),
        )
    else:
        adjusted_device_size = list(layout.device_layout.device_size)
        stick_dim_idx = -3 if len(adjusted_device_size) > 2 else -2
        old = get_elem_in_stick(layout.dtype)
        new = get_elem_in_stick(dtype)
        if old > new:
            scaling_factor = old / new
            adjusted_device_size[-1] = int(adjusted_device_size[-1] * scaling_factor)
            adjusted_device_size[stick_dim_idx] = int(
                (adjusted_device_size[stick_dim_idx] + scaling_factor - 1)
                / scaling_factor
            )
        else:
            scaling_factor = new / old
            adjusted_device_size[-1] = int(adjusted_device_size[-1] / scaling_factor)
            adjusted_device_size[stick_dim_idx] = int(
                adjusted_device_size[stick_dim_idx] * scaling_factor
            )
        return SpyreTensorLayout(
            adjusted_device_size, layout.device_layout.dim_map, get_device_dtype(dtype)
        )


def pointwise_layout(n: SchedulerNode, args: list[SchedNodeArg]) -> FixedTiledLayout:
    pw: Pointwise = n.node.data
    output: FixedLayout = n.node.get_layout()
    output_dep = next(iter(n.read_writes.writes))
    origin_node = next(iter(pw.origins))
    op = origin_node.target

    if len(args) == 1:
        x = args[0]
        x_stl = x.layout.device_layout
        match op:
            case spyreop.slice.default:
                if not is_sparse(x_stl):
                    raise Unsupported("slice on non-sparse tensor")
                if len(x.layout.size) != 1:
                    raise Unsupported("slice on non 1-D tensor")
                stl = SpyreTensorLayout(output.size, output.dtype)
                return FixedTiledLayout(
                    output.device, output.dtype, output.size, output.stride, stl
                )

            case spyreop.swap.default:
                if not is_sparse(x_stl):
                    raise Unsupported("swap on non-sparse tensor")
                if len(x.layout.size) != 1:
                    raise Unsupported("swap on non 1-D tensor")
                stl = SpyreTensorLayout(output.size, output.dtype, [0, -1])
                return FixedTiledLayout(
                    output.device, output.dtype, output.size, output.stride, stl
                )

            case aten.clone.default:
                if is_sparse(x_stl):
                    # TODO: Determine whether we already support cloning a sparse tensor
                    #       or what functionality needs to be added to enable it.  Restickify?
                    raise Unsupported("clone on sparse tensor")

                # Clone is generated by an explicit `contiguous()`; on spyre that means use the default row major tiling.
                stl = SpyreTensorLayout(
                    output.size, output.dtype, list(range(len(output.size)))
                )
                return FixedTiledLayout(
                    output.device, output.dtype, output.size, output.stride, stl
                )

            case _:
                in_coords = host_coordinates(x.layout, x.dep)
                out_coords = host_coordinates(output, output_dep)
                if in_coords == out_coords and x.dep.index == output_dep.index:
                    # Input and output tensors are being accessed identically.
                    # We can simply propagate the device_layout.
                    stl = device_layout_like(x.layout, output.dtype)
                else:
                    # TODO: This needs further work
                    # Use row major adjusted to put stick dimension last and any
                    # non-stick size one dimensions in the output to the interior
                    # to avoid tiling them.
                    in_device_coords = device_coordinates(x.layout, x.dep)
                    stick_expr = in_device_coords[-1]
                    if is_sparse(x_stl):
                        raise Unsupported("TODO: unary op with view on sparse tensor")

                    if stick_expr in out_coords:
                        out_stick_dim = out_coords.index(stick_expr)
                    else:
                        out_stick_dim = -1
                    dim_order = [
                        d
                        for d in range(len(output.size))
                        if d != out_stick_dim and out_coords[d] != 0
                    ]
                    dim_order += [
                        d for d in range(len(output.size)) if out_coords[d] == 0
                    ]
                    dim_order += [out_stick_dim]
                    stl = SpyreTensorLayout(output.size, output.dtype, dim_order)

                return FixedTiledLayout(
                    output.device, output.dtype, output.size, output.stride, stl
                )

    elif op == spyreop.layernormnorm.default:
        # Output layout is determined by layout of first argument only
        x = args[0]
        x_stl = x.layout.device_layout
        if x.layout.size != output.size or x.layout.stride != output.stride:
            raise Unsupported(
                f"views not supported for spyre.layernormnorm({x.layout.size})=>{output.size}) "
            )
        stl = SpyreTensorLayout(x_stl.device_size, x_stl.dim_map, x_stl.device_dtype)
        return FixedTiledLayout(
            output.device, output.dtype, output.size, output.stride, stl
        )
    else:
        in_coords = [host_coordinates(arg.layout, arg.dep) for arg in args]
        in_device_coords = [device_coordinates(arg.layout, arg.dep) for arg in args]
        out_coords = host_coordinates(output, output_dep)

        # Stick compatability check.
        # For all tensors whose stick dimension is being iterated over,
        # the indexing expression must be identical.
        stick_exprs = set()
        for idc in in_device_coords:
            if idc[-1] != 0:
                stick_exprs.add(idc[-1])

        if len(stick_exprs) > 1:
            # TODO: This is a legal PyTorch operation that we cannot execute without inserting restickify operations.
            raise Unsupported(
                f"Spyre limitation: pointwise op with nonuniform stick indexing: {stick_exprs}"
            )

        # See if the indexing across all inputs and the output is identical.
        can_use_same_layout = True
        for arg, arg_coors in zip(args, in_coords):
            if arg_coors != out_coords or arg.dep.index != output_dep.index:
                can_use_same_layout = False
                break

        if can_use_same_layout:
            # Identical indexing. Therefore no views or broadcasts. Just propagate layout
            stl = device_layout_like(args[0].layout, output.dtype)
        else:
            # Use row major adjusted to put stick dimension last
            # TODO: Should we also push size 1 dims to the interior here like in unary above??
            if len(stick_exprs) == 0:
                raise Unsupported(
                    "pointwise op with views/broadcasts without stick dim"
                )

            stick_expr = next(iter(stick_exprs))
            if stick_expr in out_coords:
                out_stick_dim = out_coords.index(stick_expr)
            else:
                out_stick_dim = -1

            dim_order = [d for d in range(len(output.size)) if d != out_stick_dim]
            dim_order += [out_stick_dim]
            stl = SpyreTensorLayout(output.size, output.dtype, dim_order)

        result = FixedTiledLayout(
            output.device, output.dtype, output.size, output.stride, stl
        )

        if logger.isEnabledFor(logging.DEBUG):
            input_info = ", ".join(
                [f"in{i}:{list(arg.layout.size)}" for i, arg in enumerate(args)]
            )
            logger.debug(
                f"{op.__name__} layout: {input_info} -> out:{list(result.size)}, "
                f"device_size={list(result.device_layout.device_size)}"
            )

        return result


def reduction_layout(n: SchedulerNode, args: list[SchedNodeArg]) -> FixedTiledLayout:
    red: Reduction = n.node.data
    output: FixedLayout = n.node.get_layout()
    output_dep = next(iter(n.read_writes.writes))
    if (
        red.reduction_type == MATMUL_REDUCTION_OP
        or red.reduction_type == BATCH_MATMUL_OP
    ):
        x = args[0]
        y = args[1]
        x_stl = x.layout.device_layout
        y_stl = y.layout.device_layout
        if is_sparse(x_stl) or is_sparse(y_stl):
            raise Unsupported(f"{red.reduction_type} on sparse tensor {x_stl} {y_stl}")

        x_coords = host_coordinates(x.layout, x.dep)
        x_dev_coords = device_coordinates(x.layout, x.dep)
        y_coords = host_coordinates(y.layout, y.dep)
        y_dev_coords = device_coordinates(y.layout, y.dep)
        out_coords = host_coordinates(output, output_dep)
        x_stick_expr = x_dev_coords[-1]
        y_stick_expr = y_dev_coords[-1]
        try:
            x_stick_dim = x_coords.index(x_stick_expr)
            y_stick_dim = y_coords.index(y_stick_expr)
        except ValueError:
            raise Unsupported(
                f"{red.reduction_type}: failed to map stick_dims to host coords"
            )

        if (
            x_stick_dim != len(x.layout.size) - 1
            or y_stick_dim != len(y.layout.size) - 1
            or not isinstance(x_stick_expr, Symbol)
            or not isinstance(y_stick_expr, Symbol)
        ):
            # TODO: This is a legal PyTorch operation that we cannot execute without inserting restickify operations.
            raise Unsupported(
                f"Spyre limitation: {red.reduction_type} requires restickify"
            )
        try:
            out_stick_dim = out_coords.index(y_stick_expr)
        except ValueError:
            raise Unsupported(
                f"{red.reduction_type}: failed to map output stick_dim to host coords {out_coords} {y_stick_expr}"
            )

        out_dims = len(output.size)
        out_dim_order = list(range(out_dims - 2))
        if out_stick_dim == out_dims - 1:
            out_dim_order = out_dim_order + [out_dims - 2, out_dims - 1]
        else:
            out_dim_order = out_dim_order + [out_dims - 1, out_dims - 2]
        stl = SpyreTensorLayout(output.size, output.dtype, out_dim_order)
        return FixedTiledLayout(
            output.device, output.dtype, output.size, output.stride, stl
        )
    elif red.reduction_type == "exx2":
        x = args[0]
        x_stl = x.layout.device_layout
        if is_sparse(x_stl) or x_stl.host_stick_dim() != (len(x.layout.size) - 1):
            raise Unsupported(f"exx2 unsupported layout {x_stl}")
        dim_map = list(range(len(output.size))) + [-1]
        stl = SpyreTensorLayout(output.size, output.dtype, dim_map)
        return FixedTiledLayout(
            output.device, output.dtype, output.size, output.stride, stl
        )
    else:
        x = args[0]
        x_stl = x.layout.device_layout

        x_coords = host_coordinates(x.layout, x.dep)
        x_dev_coords = device_coordinates(x.layout, x.dep)
        out_coords = host_coordinates(output, output_dep)
        x_stick_expr = x_dev_coords[-1]
        if not isinstance(x_stick_expr, Symbol) or x_stick_expr == 0:
            # TODO: Not clear if we can do this or not; defer for now
            raise Unsupported("reduction with transposed stick dim")
        sparse = x_stick_expr not in out_coords
        if sparse:
            out_dim_order = list(range(len(output.size))) + [-1]
        else:
            out_stick_dim = out_coords.index(x_stick_expr)
            out_dim_order = [
                d for d in list(range(len(output.size))) if d != out_stick_dim
            ]
            out_dim_order = out_dim_order + [out_stick_dim]
        stl = SpyreTensorLayout(output.size, output.dtype, out_dim_order)
        result = FixedTiledLayout(
            output.device, output.dtype, output.size, output.stride, stl
        )

        if logger.isEnabledFor(logging.DEBUG):
            logger.debug(
                f"{red.reduction_type} layout: in:{list(args[0].layout.size)} -> out:{list(result.size)}, "
                f"device_size={list(result.device_layout.device_size)}"
            )

        return result


def generic_layout(n: ExternKernelSchedulerNode) -> FixedTiledLayout:
    output: FixedLayout = n.node.get_layout()
    # Use the generic stick format
    stl = SpyreTensorLayout(output.size, output.dtype)
    return FixedTiledLayout(
        output.device, output.dtype, output.size, output.stride, stl
    )


def propagate_spyre_tensor_layouts(
    nodes: list[BaseSchedulerNode],
) -> list[BaseSchedulerNode]:
    # Convert InputBuffers from FixedLayout to FixedTiledLayouts
    if len(V.graph.graph_input_names) > 0:
        for name, real_input in zip(V.graph.graph_input_names, V.get_real_inputs()):
            if isinstance(real_input, torch.Tensor):
                stl = real_input.device_tensor_layout()
                if stl is None:
                    # All spyre tensors are created with device layouts.
                    # Therefore we expect all graph inputs to have them.
                    raise Unsupported(
                        f"missing device_tensor_layout on graph input {name}"
                    )

                tb = V.graph.graph_inputs[name]
                if (
                    not isinstance(tb, TensorBox)
                    or not isinstance(tb.data, StorageBox)
                    or not isinstance(tb.data.data, InputBuffer)
                ):
                    raise Unsupported(
                        "graph input {name} is not a TensorBox(StorageBox(InputBuffer))"
                    )
                ptl = tb.data.data.layout
                if not isinstance(ptl, FixedLayout):
                    raise Unsupported("graph input {name} does not have a FixedLayout")
                tb.data.data.layout = FixedTiledLayout(
                    ptl.device, ptl.dtype, ptl.size, ptl.stride, stl
                )

    # Nodes are in topological order (guarenteed by caller).
    # Visit them and use the inputs' FixedTiledLayouts and the operation being
    # performed by the node to convert its output FixedLayout to a FixedTiledLayout.

    it = iter(nodes)
    for n in it:
        if isinstance(n, SchedulerNode) and isinstance(n.node, ComputedBuffer):
            n.node.decide_layout()
            if isinstance(n.node.data, Pointwise):
                output_layout = pointwise_layout(n, get_mem_deps(n))
                n.node.layout = output_layout
            elif isinstance(n.node.data, Reduction):
                output_layout = reduction_layout(n, get_mem_deps(n))
                n.node.layout = output_layout
            else:
                logger.warning(f"Warning: unhandled node type {type(n.node)}")
        elif isinstance(n, ExternKernelSchedulerNode):
            if isinstance(n.node, FallbackKernel):
                n = next(it, None)
                if not (
                    isinstance(n, ExternKernelSchedulerNode)
                    and isinstance(n.node, MultiOutput)
                ):
                    raise RuntimeError("FallbackKernel must be followed by MultiOutput")

                output_layout = generic_layout(n)
                n.node.layout = output_layout
            else:
                logger.warning(f"unhandled node type {type(n.node)}")
        elif isinstance(n, NopKernelSchedulerNode):
            output_layout = generic_layout(n)
            n.node.layout = output_layout
        else:
            logger.warning(f"unhandled scheduler node type {type(n)}")

    return nodes
