# Copyright 2025 The Torch-Spyre Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import logging


import torch
from .logging_utils import get_inductor_logger
from torch._inductor.ir import (
    ComputedBuffer,
    ExternKernel,
    FallbackKernel,
    FixedLayout,
    InputBuffer,
    MutationLayoutSHOULDREMOVE,
    MultiOutput,
    Operation,
    Pointwise,
    Reduction,
    StorageBox,
    TensorBox,
)
from torch._inductor.dependencies import MemoryDep
from torch._inductor.scheduler import SchedulerNode
from torch._inductor.virtualized import V

from torch_spyre._C import (
    SpyreTensorLayout,
    get_device_dtype,
    get_elem_in_stick,
)
from .errors import Unsupported
from .constants import MATMUL_REDUCTION_OP, BATCH_MATMUL_OP
from .ir import FixedTiledLayout
from .pass_utils import (
    SchedNodeArg,
    get_mem_deps_from_rw,
    host_coordinates,
    device_coordinates,
)
from .views import matching_dim

logger = get_inductor_logger("stickify")

aten = torch.ops.aten
spyreop = torch.ops.spyre


def same_device_size(t1: torch.dtype, t2: torch.dtype) -> bool:
    return get_elem_in_stick(t1) == get_elem_in_stick(t2)


def pointwise_layout(
    data: Pointwise,
    output: FixedLayout,
    output_dep: MemoryDep,
    args: list[SchedNodeArg],
) -> FixedTiledLayout:
    origin_node = next(iter(data.origins))
    op = origin_node.target

    if len(args) == 1:
        x = args[0]
        match op:
            case aten.clone.default:
                # Clone is generated by an explicit `contiguous()`; on spyre that means use the default row major tiling.
                stl = SpyreTensorLayout(
                    output.size,
                    output.stride,
                    output.dtype,
                    list(range(len(output.size))),
                )
                return FixedTiledLayout(
                    output.device, output.dtype, output.size, output.stride, stl
                )

            case spyreop.overwrite.default:
                stl = SpyreTensorLayout(output.size, output.dtype)
                return FixedTiledLayout(
                    output.device, output.dtype, output.size, output.stride, stl
                )
            case _:
                x_stl = x.layout.device_layout
                in_coords = host_coordinates(x.layout, x.dep)
                out_coords = host_coordinates(output, output_dep)
                if (
                    in_coords == out_coords
                    and x.dep.index == output_dep.index
                    and same_device_size(x.layout.dtype, output.dtype)
                ):
                    # Input and output tensors are being accessed identically and elem size is the same.
                    # We can simply propagate the device_layout.
                    stl = SpyreTensorLayout(
                        x_stl.device_size,
                        x_stl.dim_map,
                        x_stl.stride_map,
                        get_device_dtype(output.dtype),
                    )
                else:
                    # TODO: Once we eliminate the dim_map from the STL,
                    #       we should be able to preserve the input stride_map
                    #       unless the operation is changing elems_per_stick.
                    #       Until then, use the default layout for a mostly row major dimension
                    #       ordering, adjusted to put the stick dimension last and move all
                    #       non-stick size one dimensions to the right to avoid tiling them.
                    in_device_coords = device_coordinates(x.layout, x.dep)
                    stick_expr = in_device_coords[-1]
                    maybe_stick_dim = matching_dim(out_coords, stick_expr)
                    out_stick_dim = -1 if maybe_stick_dim is None else maybe_stick_dim
                    dim_order = [
                        d
                        for d in range(len(output.size))
                        if d != out_stick_dim and out_coords[d] != 0
                    ]
                    dim_order += [
                        d
                        for d in range(len(output.size))
                        if d != out_stick_dim and out_coords[d] == 0
                    ]
                    dim_order += [out_stick_dim]
                    stl = SpyreTensorLayout(
                        output.size, output.stride, output.dtype, dim_order
                    )

                return FixedTiledLayout(
                    output.device, output.dtype, output.size, output.stride, stl
                )

    elif op == spyreop.layernormnorm.default:
        # Output layout is determined by layout of first argument only
        x = args[0]
        x_stl = x.layout.device_layout
        if x.layout.size != output.size or x.layout.stride != output.stride:
            raise Unsupported(
                f"views not supported for spyre.layernormnorm({x.layout.size})=>{output.size}) "
            )
        stl = SpyreTensorLayout(
            x_stl.device_size, x_stl.dim_map, x_stl.stride_map, x_stl.device_dtype
        )
        return FixedTiledLayout(
            output.device, output.dtype, output.size, output.stride, stl
        )
    else:
        in_coords = [host_coordinates(arg.layout, arg.dep) for arg in args]
        in_device_coords = [device_coordinates(arg.layout, arg.dep) for arg in args]
        out_coords = host_coordinates(output, output_dep)

        # Stick compatability check.
        # For all tensors whose stick dimension is being iterated over,
        # the indexing expression must be identical.
        stick_exprs = set()
        for idc in in_device_coords:
            if idc[-1] != 0:
                stick_exprs.add(idc[-1])

        if len(stick_exprs) > 1:
            # TODO: This is a legal PyTorch operation that we cannot execute without inserting restickify operations.
            raise Unsupported(
                f"Spyre limitation: pointwise op with nonuniform stick indexing: {stick_exprs}"
            )

        # If the indexing and device element size are identical
        # across all inputs and the output we can just propagate the device layout.
        can_use_same_layout = True
        for arg, arg_coors in zip(args, in_coords):
            if (
                arg_coors != out_coords
                or arg.dep.index != output_dep.index
                or not same_device_size(arg.layout.dtype, output.dtype)
            ):
                can_use_same_layout = False
                break

        if can_use_same_layout:
            template_stl = args[0].layout.device_layout
            stl = SpyreTensorLayout(
                template_stl.device_size,
                template_stl.dim_map,
                template_stl.stride_map,
                get_device_dtype(output.dtype),
            )
        else:
            # Use row major adjusted to put stick dimension last
            # and move all non-stick size one dimensions to the right to avoid tiling them.
            if len(stick_exprs) == 0:
                maybe_stick_dim = None
                out_stick_dim = -1
            else:
                maybe_stick_dim = matching_dim(out_coords, next(iter(stick_exprs)))
                out_stick_dim = -1 if maybe_stick_dim is None else maybe_stick_dim

            dim_order = [
                d
                for d in range(len(output.size))
                if d != out_stick_dim and out_coords[d] != 0
            ]
            dim_order += [
                d
                for d in range(len(output.size))
                if d != out_stick_dim and out_coords[d] == 0
            ]
            dim_order += [out_stick_dim]
            stl = SpyreTensorLayout(output.size, output.stride, output.dtype, dim_order)

        result = FixedTiledLayout(
            output.device, output.dtype, output.size, output.stride, stl
        )

        if logger.isEnabledFor(logging.DEBUG):
            input_info = ", ".join(
                [f"in{i}:{list(arg.layout.size)}" for i, arg in enumerate(args)]
            )
            logger.debug(
                f"{op.__name__} layout: {input_info} -> out:{list(result.size)}, "
                f"device_size={list(result.device_layout.device_size)}"
            )

        return result


def reduction_layout(
    data: Reduction,
    output: FixedLayout,
    output_dep: MemoryDep,
    args: list[SchedNodeArg],
) -> FixedTiledLayout:
    if (
        data.reduction_type == MATMUL_REDUCTION_OP
        or data.reduction_type == BATCH_MATMUL_OP
    ):
        x = args[0]
        y = args[1]
        x_coords = host_coordinates(x.layout, x.dep)
        x_dev_coords = device_coordinates(x.layout, x.dep)
        y_coords = host_coordinates(y.layout, y.dep)
        y_dev_coords = device_coordinates(y.layout, y.dep)
        out_coords = host_coordinates(output, output_dep)
        x_stick_expr = x_dev_coords[-1]
        y_stick_expr = y_dev_coords[-1]
        x_stick_dim = matching_dim(x_coords, x_stick_expr)
        y_stick_dim = matching_dim(y_coords, y_stick_expr)
        if x_stick_dim is None or y_stick_dim is None:
            raise Unsupported(
                f"{data.reduction_type}: failed to map stick_dims to host coords"
            )

        if (
            x_stick_dim != len(x.layout.size) - 1
            or y_stick_dim != len(y.layout.size) - 1
        ):
            # TODO: This is a legal PyTorch operation that we cannot execute without inserting restickify operations.
            raise Unsupported(
                f"Spyre limitation: {data.reduction_type} requires restickify"
            )
        out_stick_dim = matching_dim(out_coords, y_stick_expr)
        if out_stick_dim is None:
            raise Unsupported(
                f"{data.reduction_type}: failed to map output stick_dim to host coords {out_coords} {y_stick_expr}"
            )

        out_dims = len(output.size)
        out_dim_order = list(range(out_dims - 2))
        if out_stick_dim == out_dims - 1:
            out_dim_order = out_dim_order + [out_dims - 2, out_dims - 1]
        else:
            out_dim_order = out_dim_order + [out_dims - 1, out_dims - 2]
        stl = SpyreTensorLayout(output.size, output.stride, output.dtype, out_dim_order)
        return FixedTiledLayout(
            output.device, output.dtype, output.size, output.stride, stl
        )
    elif data.reduction_type == "exx2":
        x = args[0]
        x_coords = host_coordinates(x.layout, x.dep)
        x_dev_coords = device_coordinates(x.layout, x.dep)
        x_stick_expr = x_dev_coords[-1]
        x_stick_dim = matching_dim(x_coords, x_stick_expr)
        if x_stick_dim is None or x_stick_dim != len(x.layout.size) - 1:
            # TODO: Insert a restickify to enable the operation to be performed
            raise Unsupported(f"exx2: illegal device layout {x.layout}")

        dim_map = list(range(len(output.size))) + [-1]
        stl = SpyreTensorLayout(output.size, output.stride, output.dtype, dim_map)
        return FixedTiledLayout(
            output.device, output.dtype, output.size, output.stride, stl
        )
    else:
        x = args[0]
        x_coords = host_coordinates(x.layout, x.dep)
        x_dev_coords = device_coordinates(x.layout, x.dep)
        out_coords = host_coordinates(output, output_dep)
        x_stick_expr = x_dev_coords[-1]
        out_stick_dim = matching_dim(out_coords, x_stick_expr)
        if out_stick_dim is None:
            out_dim_order = list(range(len(output.size))) + [-1]
        else:
            out_dim_order = [
                d for d in list(range(len(output.size))) if d != out_stick_dim
            ]
            out_dim_order = out_dim_order + [out_stick_dim]
        stl = SpyreTensorLayout(output.size, output.stride, output.dtype, out_dim_order)
        result = FixedTiledLayout(
            output.device, output.dtype, output.size, output.stride, stl
        )

        if logger.isEnabledFor(logging.DEBUG):
            logger.debug(
                f"{data.reduction_type} layout: in:{list(args[0].layout.size)} -> out:{list(result.size)}, "
                f"device_size={list(result.device_layout.device_size)}"
            )

        return result


def generic_layout(op: Operation) -> FixedTiledLayout:
    output: FixedLayout = op.get_layout()
    # Use the generic stick format
    stl = SpyreTensorLayout(output.size, output.dtype)
    return FixedTiledLayout(
        output.device, output.dtype, output.size, output.stride, stl
    )


def propagate_spyre_tensor_layouts(
    operations: list[Operation],
) -> None:
    # Convert InputBuffers from FixedLayout to FixedTiledLayouts
    if len(V.graph.graph_input_names) > 0:
        for name, real_input in zip(V.graph.graph_input_names, V.get_real_inputs()):
            if isinstance(real_input, torch.Tensor):
                stl = real_input.device_tensor_layout()
                if stl is None:
                    # All spyre tensors are created with device layouts.
                    # Therefore we expect all graph inputs to have them.
                    raise Unsupported(
                        f"missing device_tensor_layout on graph input {name}"
                    )

                tb = V.graph.graph_inputs[name]
                if (
                    not isinstance(tb, TensorBox)
                    or not isinstance(tb.data, StorageBox)
                    or not isinstance(tb.data.data, InputBuffer)
                ):
                    raise Unsupported(
                        "graph input {name} is not a TensorBox(StorageBox(InputBuffer))"
                    )
                ptl = tb.data.data.layout
                if not isinstance(ptl, FixedLayout):
                    raise Unsupported("graph input {name} does not have a FixedLayout")
                tb.data.data.layout = FixedTiledLayout(
                    ptl.device, ptl.dtype, ptl.size, ptl.stride, stl
                )

    # Operations are in topological order (guaranteed by GraphLowering).
    # Visit them and use the inputs' FixedTiledLayouts and the operation being
    # performed to convert each output FixedLayout to a FixedTiledLayout.

    it = iter(operations)
    for op in it:
        if op.is_no_op():
            op.layout = generic_layout(op)
        elif isinstance(op, ComputedBuffer):
            if isinstance(op.layout, MutationLayoutSHOULDREMOVE):
                # Mutation ops (e.g. spyre.overwrite) must keep their
                # MutationLayoutSHOULDREMOVE so the scheduler correctly
                # treats them as in-place writes to the target buffer.
                # Their FixedTiledLayout is assigned later in
                # propagate_mutation_layouts, after the scheduler has
                # set up mutation tracking.
                continue
            op.decide_layout()
            rw = op.get_read_writes()
            output_dep = next(iter(rw.writes))
            args = get_mem_deps_from_rw(rw)
            output = op.get_layout()
            if isinstance(op.data, Pointwise):
                op.layout = pointwise_layout(op.data, output, output_dep, args)
            elif isinstance(op.data, Reduction):
                op.layout = reduction_layout(op.data, output, output_dep, args)
            else:
                logger.warning(f"Warning: unhandled node type {type(op.data)}")
        elif isinstance(op, FallbackKernel):
            op = next(it, None)
            if not isinstance(op, MultiOutput):
                raise RuntimeError("FallbackKernel must be followed by MultiOutput")
            op.layout = generic_layout(op)
        elif isinstance(op, ExternKernel):
            logger.warning(f"unhandled node type {type(op)}")
        else:
            logger.warning(f"unhandled operation type {type(op)}")


def propagate_mutation_layouts(
    nodes: list,
) -> list:
    """
    Second phase of layout propagation for mutation ops.

    ComputedBuffers with MutationLayoutSHOULDREMOVE are skipped in
    propagate_spyre_tensor_layouts because the scheduler needs to see the
    mutation layout during its initialisation to set up mutation tracking.
    This pass runs as a _pre_fusion_custom_pass (after scheduler init) to
    assign FixedTiledLayout to those remaining mutation ops.
    """
    from .pass_utils import get_mem_deps

    for n in nodes:
        if not (isinstance(n, SchedulerNode) and isinstance(n.node, ComputedBuffer)):
            continue
        if not isinstance(n.node.layout, MutationLayoutSHOULDREMOVE):
            continue
        if isinstance(n.node.data, Pointwise):
            rw = n.read_writes
            output_dep = next(iter(rw.writes))
            args = get_mem_deps(n)
            output = n.node.get_layout()
            n.node.layout = pointwise_layout(n.node.data, output, output_dep, args)
        else:
            logger.warning(
                f"propagate_mutation_layouts: unhandled mutation op {type(n.node.data)}"
            )

    return nodes
