# Copyright 2026 The Torch-Spyre Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for torch_spyre version.

``__version__`` is written into ``torch_spyre/_version.py`` at build time by
setuptools_scm and is always a valid PEP 440 string. These tests assert shape
and invariants, never a hardcoded value.

``torch_spyre._version`` is imported directly rather than via ``import
torch_spyre`` so these run without a built ``_C`` extension.
"""

import importlib.metadata
import importlib.util
from pathlib import Path

import pytest


def _find_version_file() -> Path:
    """Locate ``torch_spyre/_version.py``, preferring the installed distribution.

    Two layouts must both work:

    * **CI wheel flow** — the prebuilt wheel is installed into site-packages and
      the checked-out ``torch_spyre/`` source tree is removed so it cannot shadow
      the installation.  The installed distribution is therefore consulted first,
      via its recorded file list.
    * **Source checkout** — ``torch_spyre/_version.py`` is generated by
      ``pip install -e .`` or ``python -m build`` and lives next to ``tests/``.
    """
    try:
        dist = importlib.metadata.distribution("torch_spyre")
    except importlib.metadata.PackageNotFoundError:
        dist = None

    if dist is not None:
        for recorded in dist.files or ():
            if recorded.parts[-2:] == ("torch_spyre", "_version.py"):
                located = Path(str(dist.locate_file(recorded))).resolve()
                if located.is_file():
                    return located

    for candidate in Path(__file__).resolve().parents:
        version_file = candidate / "torch_spyre" / "_version.py"
        if version_file.is_file():
            return version_file

    raise RuntimeError(
        "cannot locate torch_spyre/_version.py: it is neither recorded in an "
        "installed torch_spyre distribution nor present in a parent directory of "
        f"{Path(__file__).resolve()}. Run 'pip install -e .' or "
        "'python -m build --wheel' to generate it."
    )


def _load_version_module():
    """Import torch_spyre._version without importing the torch_spyre package."""
    module_path = _find_version_file()
    spec = importlib.util.spec_from_file_location("torch_spyre__version", module_path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def version_mod():
    """torch_spyre._version, imported once per module."""
    return _load_version_module()


def test_version_is_valid_pep440(version_mod):
    """__version__ must parse as a PEP 440 version, local segment included."""
    packaging_version = pytest.importorskip("packaging.version")
    packaging_version.Version(version_mod.__version__)


def test_version_is_string(version_mod):
    """__version__ must be a non-empty string."""
    assert isinstance(version_mod.__version__, str)
    assert version_mod.__version__


def test_version_has_expected_shape(version_mod):
    """__version__ must be either a clean release/RC or a dev+local string."""
    v = version_mod.__version__
    # Accepted shapes:
    #   1.0.0rc1                        (exact RC tag)
    #   1.0.0                           (exact release tag)
    #   1.0.0.dev5+main.gabc1234.b42    (snapshot build)
    assert "." in v, f"version has no dot separator: {v!r}"
