---
name: Bug Report
description: Report a bug encountered while using Torch Spyre
labels:
  - type/bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: markdown
    attributes:
      value: |
        Please fill the form below and provide as much information as possible.
        This will help project contributors to address the bug in a timely manner.

  - type: textarea
    id: problem
    attributes:
      label: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How can we reproduce it?
    validations:
      required: true

  - type: textarea
    id: userenv
    attributes:
      label: Any environmental details we need to know?
      description: Please provide details about your environment, such as the PyTorch version.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Anything else we need to know?

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
