# Copyright 2026 The Torch-Spyre Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# DO NOT EDIT THIS FILE. This is a generated file.
# Generated by convert_section_types.py at 2026-07-26 12:09:33.485692.
# JSON input: section_types.json (Last update: 2026-07-26 11:52:02.805615).

from .section_type_defs import (
    MetricDataType,
    SectionType,
    SummarizerType,
    ValueType,
)

SOURCE_JSON = "section_types.json"

VERSION = (1, 0, 0, 1)

SECTION_TYPES = (
    SectionType(name="invalid", id=0, long_name="Invalid section ID"),
    SectionType(name="host_metrics", id=1, long_name="Host resource usage"),
    SectionType(name="runtime", id=16, long_name="Runtime metrics"),
    SectionType(name="perf_counter", id=32, long_name="Performance counters"),
)

SectionType.add_id_map({entry.id: entry for entry in SECTION_TYPES})
SectionType.add_name_map({entry.name: entry for entry in SECTION_TYPES})

VALUE_TYPES = (
    ValueType(name="invalid", id=0, long_name="Invalid value type"),
    ValueType(name="int", id=1, long_name="uint64 value"),
    ValueType(name="KiB", id=2, long_name="Size in KiB"),
    ValueType(name="MiB", id=3, long_name="Size in MiB"),
    ValueType(name="GiB", id=4, long_name="Size in GiB"),
    ValueType(name="float", id=16, long_name="fp64 value"),
    ValueType(
        name="fdec1",
        id=17,
        long_name="fixed point decimal in unit of one decimal place",
    ),
)

ValueType.add_id_map({entry.id: entry for entry in VALUE_TYPES})
ValueType.add_name_map({entry.name: entry for entry in VALUE_TYPES})

SUMMARIZER_TYPES = (
    SummarizerType(name="invalid", id=0, long_name="Invalid summarizer"),
    SummarizerType(
        name="first", id=1, long_name="Take the first element of a data array"
    ),
    SummarizerType(
        name="last", id=2, long_name="Take the last element of a data array"
    ),
    SummarizerType(name="sum", id=17, long_name="Accumulate values in a data array"),
    SummarizerType(
        name="avg", id=18, long_name="Calculate an average of values in a data array"
    ),
    SummarizerType(
        name="max", id=19, long_name="Pick the maximum element in a data array"
    ),
)

SummarizerType.add_id_map({entry.id: entry for entry in SUMMARIZER_TYPES})
SummarizerType.add_name_map({entry.name: entry for entry in SUMMARIZER_TYPES})

METRIC_TYPES = (
    MetricDataType(
        section="invalid",
        name="invalid",
        id=0,
        type="invalid",
        summarizer="invalid",
        long_name="Invalid data type ID",
    ),
    MetricDataType(
        section="host_metrics",
        name="hostcpu",
        id=1,
        type="int",
        summarizer="avg",
        long_name="Host CPU utilization",
    ),
    MetricDataType(
        section="host_metrics",
        name="hostmem",
        id=2,
        type="int",
        summarizer="avg",
        long_name="Host memory utilization",
    ),
    MetricDataType(
        section="host_metrics",
        name="hstrxnet",
        id=3,
        type="KiB",
        summarizer="sum",
        long_name="Host network receive",
    ),
    MetricDataType(
        section="host_metrics",
        name="hsttxnet",
        id=4,
        type="KiB",
        summarizer="sum",
        long_name="Host network send",
    ),
    MetricDataType(
        section="host_metrics",
        name="hstrdblk",
        id=5,
        type="KiB",
        summarizer="sum",
        long_name="Host block storage read",
    ),
    MetricDataType(
        section="host_metrics",
        name="hstwrblk",
        id=6,
        type="KiB",
        summarizer="sum",
        long_name="Host block storage write",
    ),
    MetricDataType(
        section="perf_counter",
        name="pwr",
        id=16,
        type="fdec1",
        summarizer="first",
        long_name="Power consumption",
    ),
    MetricDataType(
        section="perf_counter",
        name="tempr",
        id=17,
        type="fdec1",
        summarizer="max",
        long_name="Device temperature",
    ),
    MetricDataType(
        section="perf_counter",
        name="rdmem",
        id=18,
        type="KiB",
        summarizer="sum",
        long_name="Device memory read",
    ),
    MetricDataType(
        section="perf_counter",
        name="wrmem",
        id=19,
        type="KiB",
        summarizer="sum",
        long_name="Device memory write",
    ),
    MetricDataType(
        section="perf_counter",
        name="rxpci",
        id=20,
        type="KiB",
        summarizer="sum",
        long_name="Host-to-device read",
    ),
    MetricDataType(
        section="perf_counter",
        name="txpci",
        id=21,
        type="KiB",
        summarizer="sum",
        long_name="Device-to-host write",
    ),
    MetricDataType(
        section="perf_counter",
        name="rdrdma",
        id=22,
        type="KiB",
        summarizer="sum",
        long_name="RDMA read",
    ),
    MetricDataType(
        section="perf_counter",
        name="wrrdma",
        id=23,
        type="KiB",
        summarizer="sum",
        long_name="RDMA write",
    ),
    MetricDataType(
        section="runtime",
        name="avgmem",
        id=129,
        type="MiB",
        summarizer="avg",
        long_name="Average device memory usage",
    ),
    MetricDataType(
        section="runtime",
        name="peakmem",
        id=130,
        type="MiB",
        summarizer="max",
        long_name="Peak device memory usage",
    ),
)

MetricDataType.add_id_map({entry.id: entry for entry in METRIC_TYPES})
MetricDataType.add_name_map({entry.name: entry for entry in METRIC_TYPES})
